# SPDX-FileCopyrightText: NOI Techpark <digital@noi.bz.it>
#
# SPDX-License-Identifier: CC0-1.0

version: "3.4"
services:
  api:
    build:
      context: .
      dockerfile: infrastructure/docker/java.dockerfile
      target: dev
    volumes:
      - ./:/code
    working_dir: /code
    command: "mvn -B spring-boot:run" # -Dspring-boot.run.profiles=local"
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      DB_URL: ${DB_URL}
      DB_USERNAME: epaper
      DB_PASSWORD: epaper
      APP_DEBUG: epaper
    tty: true
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
  postgres:
    image: "postgres:11-alpine"
    environment:
      POSTGRES_DB: epaper
      POSTGRES_USER: epaper
      POSTGRES_PASSWORD: epaper
    hostname: postgres
    volumes:
      - /tmp/epaper_pgdata:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"