services:
  app:
    image: ${DOCKER_IMAGE}:${DOCKER_TAG}
    command: "mvn spring-boot:run"
    restart: unless-stopped
    env_file:
      - .env
    environment:
      SERVER_PORT: ${SERVER_PORT}
      _JAVA_OPTIONS: ${JAVA_OPTIONS}
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
      - "1100:80"
